---
title: "Introduction"
author: "Eva Zhang"
date: "4/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Research Question
Is there a difference between the way Prof. Alex Shpenev tweets and Prof. Eugen 
Dimant tweets?


# Methodology
We will conduct text analysis of tweets by using sklearn in Python 
to do machine learning.
We split the data into test and train data, and we transform the texts of 
tweets into numeric data by tokenizing the tweets.

We use the **count vectorizer** approach to count the frequency of the words, and we 
getting rid of words that do not have much meaning or words that are too uncommon. 

We use the **TF-IDF vectorizer** approach to calculate the frequency of 
the words and weigh in favor of words that are relatively rare overall, since
they might be more important compared to words that frequently appear. 


We run a Naive **Bayes Model**. 
Since we have a limited number of tweets, we assume each word is independent 
from each other to develop this relatively simple model.

We also use the **Linear Support Vector Classifier** approach.

